= Должностная инструкция руководителя проектов по созданию сайтов

== 1 Общие положения

// TODO: Уточнить категорию
1.1 Руководитель проектов по созданию сайтов относится к категории специалистов.

1.2 Назначение и освобождение от должности руководителя проектов по созданию сайтов производится приказом ректора университета по представлению проректора по стратегическому развитию и цифровизации.

1.3 Руководитель проектов по созданию сайтов входит в состав Отдела облачных и сетевых технологий (далее -- Отдел ОСТ), и подчиняется непосредственно руководителю Отдела ОСТ, руководителю Центра развития цифровых технологий (далее -- ЦРЦТ) руководителю Управления стратегических инициатив и внешних связей (далее -- УСИиВС), проректору по стратегическому развитию и цифровизации.

1.4 На должность руководителя проектов по созданию сайтов назначается лицо, имеющее высшее профессиональное (математическое, техническое или инженерно-экономическое) образование, без предъявления требований к стажу работы, или среднее профессиональное (техническое или инженерно-экономическое) образование и стаж работы в должности программиста не менее 3 лет, либо других должностях, замещаемых специалистами со средним профессиональным образованием, не менее 5 лет. 

1.5 Руководитель проектов по созданию сайтов должен знать и уметь применять на практике:

* особенности программирования и обмена данными;
* языки программирования и инструментарий разработки программного обеспечения на соответствующих языках; 
* методологии и технологии разработки программного обеспечения;
* средства и методы объектно-ориентированного проектирования и разработки;
* основные методы и средства эффективного проектирования и разработки программных продуктов;
* проектирование и отладку автономных  распределённых и многопоточных приложений;
* основы теории организации и применения баз данных;
* принципы поддержки целостности конфигурации в течение жизненного цикла разработки программного обеспечения;
* основные принципы управления качеством программного продукта;
* методы оценки сроков и стоимости разработки;
* методы и средства разработки тестовых сценариев и тестового кода;
* методы и технологии тестирования и ревьюирования кода и проектной документации для контроля достижения заданной функциональности и качества в программном проекте;
* методы тестирования программного обеспечения;
* методы и технологии разработки формализованных требований и спецификаций для тестов по формальным описаниям;
* внутренние нормы и регламенты разработки;
* модели и методологии жизненного цикла разработки программного обеспечения;
* принципы идентификации и планирования ресурсов;
* принципы проектного подхода к разработке программного обеспечения и соотношения проекта и жизненного цикла;
* разработку и ведение проектной документации в соответствии со стандартами;
* методы и средства сбора требований, принципы взаимодействия с заказчиком; разработку формализованных требований для основного и тестового кода;
* методы оценки компетенций разработчиков; принципы оценки сроков и стоимости разработки, идентификации и планирования ресурсов;
* визуальные языки моделирования: UML, потоки данных, ER-диаграммы, бизнес-процессы.
* основы применения CASE-средств в технологических процессах; 
* основы защиты информации в сетях; использование SSL, TLS; сертификаты;
* основы организации и администрирования серверных ОС семейств Windows и Unix;
* администрирование веб-сервера (IIS 6/7/8, Apache); публикацию сайта из Интернет;
* основы организации сетей TCP/IP;
* основы теории организации и применения баз данных, иметь опыт работы с MS SQL, MySQL;
* основы управления изменениями кода и конфигурации;
* основы веб-дизайна и разработки эффективных пользовательских интерфейсов; 
* отраслевую нормативно-техническую документацию, специальную литературу, внутренние нормы и регламенты разработки;
* принципы архитектурного дизайна программного обеспечения, в частности,  веб-приложений;
* принципы управления версиями и релизами программного обеспечения;
* стандартные алгоритмы и структуры данных, области их применимости;
* этапы и принципы управления качеством процессов разработки в течение жизненного цикла производства программного обеспечения;
* языковые средства веб-разработки: HTML+CSS, JavaScript, PHP, ASP.NET (C#, VB.NET), AJAX, XML+XSL, SQL.
* инструментарий разработки веб-приложений:Visual Studio .NET, Dreamweaver и др.;
* системы управления контентом: Dotnetnuke, Joomla! и др.;
* основы обработки и подготовки изображений и видеоматериалов к публикации, иметь опыт работы в Photoshop, Fireworks, VirtualDUB и т.п.;
* современные технологии в области работы ИТ-специалиста;
* русский язык и культура речи, технический английский;
* законы, инструкции и руководящие документы, необходимые для работы УСИиВС;
* основы организации труда и законодательство о труде;
* правила внутреннего трудового распорядка;
* правила и нормы охраны труда, техники безопасности и противопожарной защиты.

1.6 Руководитель проектов по созданию сайтов в своей деятельности руководствуется:

* Уставом университета;
* Положением о структурном подразделении (ПСП) УСИиВС;
* Положением о веб-сайтах университета;
* Настоящей должностной инструкцией.

1.7 На время отсутствия руководителя проекта по созданию сайтов (отпуск, болезнь, пр.) его обязанности исполняет лицо, назначенное приказом ректора по представлению проректора по стратегическому развитию и цифровизации. Данное лицо приобретает соответствующие права и несет ответственность за качественное и своевременное исполнение возложенных на него обязанностей.

== 2 Основные функции и обязанности

2.1 Основные функции руководителя проектов по созданию сайтов:

* контроль и поддержание работоспособности официального сайта университета;
* администрирование официального сайта университета;
* информационная поддержка официального сайта университета;
* разработка шаблонов оформления страниц и модулей;
* продвижение сайта и поисковая оптимизация (SEO); 
* руководство и участие в разработке проектов, расширяющих функциональность сайта;
* обучение и консультирование персонала в рамках своей компетенции.

2.2 Должностные обязанности руководителя проектов по созданию сайтов:

* сбор и анализ требований к функциональности и оформлению сайта, создание сценариев использования функциональности сайта и отдельных модулей;
* формализация и контроль корректности выявленных требований;
* разработка требований к необходимым техническим ресурсам;
* разработка кода шаблонов и программных модулей на основе готовых спецификаций;
* отладка кода на уровне модулей, межмодульных взаимодействий и взаимодействий с пользователем и системой управления контента;
* проектирование распределенной и многопоточной организации создаваемых приложений;
* интеграция существующих и созданных программных компонент;
* анализ и оптимизация исполнимого кода и кода веб-страниц c использованием инструментальных средств, для повышения качества изделий и производительности разработки;
* планирование тестирования сайта и разработка тестовых наборов и процедур;
* разработка и ведение необходимой проектной и пользовательской документации;
* сдача документации и программного обеспечения заказчику;
* управление выполнением проекта, руководство проектной группой;
* взаимодействие с заказчиками, потенциальными пользователями, другими группами УСИиВС;
* оценка качества программных средств проекта;
* анализ эффективности инструментальных средств для выполнения проектов;
* участие в аттестации созданного программного обеспечения и шаблонов оформления;
* участие в совершенствовании процесса разработки в рабочих группах;
* участие в выработке проектных стандартов разработки;
* поисковая оптимизация страниц сайта (SEO), включая создание метаописаний;
* регистрация сайта в интернет-каталогах, в т.ч. тематических;
* консультация заинтересованного персонала (студентов университета, методистов кафедр) по основам веб-дизайна и управлению контентом сайта;
* создание на сайте информационных разделов для отделов и служб университета;
* обновление содержимого разделов на основе предоставленной информации;
* администрирование и модерирование форума и блогов, связь с пользователями;
* установка и настройка базового программного обеспечения веб-сервера;
* поиск и размещение на сайте материалов и ссылок, соответствующих тематике сайта; 
* планирование проекта и проведение совещаний по поводу эффективной работы сайта;
* управление персоналом в рамках выполнения проектов и работа в команде;
* анализ результатов выполненных проектов, и обобщение эффективных технологий и проектных решений;  
* планирование выполнения работ по совершенствованию процесса управления сайтом;
* развитие в себе аккуратности, аналитического мышления, методичности, ответственности, дисциплинированности, коммуникабельности, исполнительности, организованности и инициативности;
* планирование и организация собственной работы;
* организация самообучения и повышения своей квалификации;
* освоение новых методов и технологий в области информационных систем;
* чтение профессиональной литературы на английском языке;
* письменное и устное изложение своих предложений и полученных результатов для различных аудиторий.

== 3 Права

3.1 Руководитель проектов по созданию сайтов имеет право:

* знакомиться и участвовать в разработке проектов решений руководства университета и УСИиВС, касающихся его деятельности;
* вносить на рассмотрение руководства университета предложения по совершенствованию работы, связанной с предусмотренными настоящей инструкцией обязанностями;
* запрашивать лично или по поручению непосредственного руководителя у руководителей подразделений университета и специалистов информацию и документы, необходимые для выполнения его должностных обязанностей;
* требовать от руководства УСИиВС оказания содействия в исполнении своих должностных обязанностей;
* принимать решения в рамках профессиональной компетенции;
* участвовать в программах сертификации и повышения квалификации.

== 4 Ответственность

4.1 Руководитель проектов по созданию сайтов несет ответственность:

* за ненадлежащее исполнение или неисполнение своих должностных обязанностей, предусмотренных настоящей должностной инструкцией - в порядке, установленном действующим трудовым законодательством Российской Федерации;
* за правонарушения, совершенные в процессе своей деятельности - в порядке, установленном действующим административным, уголовным и гражданским законодательством Российской Федерации;
* за причинение ущерба университету - в порядке, установленном действующим трудовым законодательством Российской Федерации;
* за некачественное выполнение порученной работы в установленные сроки, несоблюдение правил внутреннего трудового распорядка, техники безопасности и производственной санитарии;
* за несоблюдение правил делового общения, норм служебного этикета, служебной субординации.
