= Должностная инструкция руководителя проектов по созданию сайтов

== 1. Общие положения

1.1 Руководитель проектов по созданию сайтов отдела облачных и сетевых технологий (далее -- отдела ОСТ) центра развития цифровых технологий (далее -- ЦРЦТ) управления стратегических инициатив и внешних связей (далее -- УСИиВС) относится к категории руководителей.

1.2 Для работы руководителем проектов по созданию сайтов принимается лицо, имеющее высшее образование в области информационных систем и технологий, а также стаж работы не менее трех лет в области создания и сопровождения информационных ресурсов (далее -- ИР). Рекомендуется: дополнительное профессиональное образование (программы повышения квалификации в области проектного менеджмента).

1.3 Назначение и освобождение от должности руководителя проектов по созданию сайтов производится приказом ректора университета по представлению руководителя отдела ОСТ и проректора по стратегическому развитию и цифровизации, согласованного с руководителем ЦРЦТ и начальником УСИиВС.

1.4 Руководитель проектов по созданию сайтов подчиняется непосредственно руководителю отдела ОСТ.

1.5 На время отсутствия руководителя проекта по созданию сайтов (отпуск, болезнь, пр.) его обязанности исполняет лицо, назначенное приказом ректора по представлению проректора по стратегическому развитию и цифровизации. Данное лицо приобретает соответствующие права и несет ответственность за качественное и своевременное исполнение возложенных на него обязанностей. 

1.6 Руководитель проектов по созданию сайтов должен знать:

* методы и средства планирования и контроля (мониторинга) исполнения планов;
* методы оценки качества плана разработки программного продукта (ресурсы, сроки, риски);
* основные принципы и методы управления персоналом;
* правила редактирования научно-технической документации;
* методы повышения читаемости программного кода;
* методы принятия управленческих решений;
* принципы построения архитектуры ИР;
* методологию и средства проектирования ИР;
* методы и средства проектирования баз данных;
* методы и средства проектирования интерфейсов;
* методологию функциональной стандартизации для открытых систем;
* нормативно-технические документы (стандарты и регламенты), описывающие требования к проектной и технической документации, процессы оценки сложности, трудоемкости, сроков выполнения работ;
* методы оценки сложности, трудоемкости и сроков выполнения работ;
* программные средства для оценки сложности, трудоемкости и сроков выполнения работ;
* нормативные документы, определяющие требования к проверке работоспособности программного кода;
* основные принципы отладки программного кода;
* основные виды диагностических данных и способы их представления;
* основные методы измерения и оценки характеристик программного обеспечения;
* методы подготовки тестовых наборов данных;
* методы и средства проверки работоспособности программного обеспечения;
* методы разработки, анализа и проектирования ИР;
* коллективную среду разработки программного обеспечения и систему контроля версий;
* методы и средства проверки работоспособности ИР;

1.7 Руководитель проектов по созданию сайтов должен уметь:

* применять методы и средства планирования и контроля (мониторинга) исполнения планов;
* применять основные принципы и методы управления персоналом;
* применять нормативно-технические документы (стандарты и регламенты), лучшие мировые практики управления процессом разработки программного продукта;
* составлять планы процесса разработки программного продукта;
* оценивать качество плана разработки программного продукта (ресурсы, сроки, риски);
* наблюдать за исполнением планов разработки программного продукта;
* корректировать план разработки программного продукта;
* применять коллективную среду документирования программного обеспечения;
* применять методы принятия управленческих решений;
* применять принципы построения архитектуры программного обеспечения и виды архитектур программного обеспечения;
* применять методологию и средства проектирования программного обеспечения;
* применять методы и средства проектирования баз данных;
* применять методы и средства проектирования интерфейсов;
* применять методологию функциональной стандартизации для открытых систем;
* взаимодействовать с подразделениями организации в рамках процесса проектирования ИР, структуры базы данных, программных интерфейсов;
* применять методы и средства оценки сложности, трудоемкости и сроков выполнения работ;
* производить подготовку тестовых наборов данных;
* применять методы и средства проверки работоспособности ИР;
* интерпретировать данные журналов сообщений, протоколов;
* использовать возможности имеющейся технической и/или программной архитектуры;
* применять коллективную среду разработки программного обеспечения и систему контроля версий;
* проектировать архитектуру ИР;
* проверять (верифицировать) архитектуру ИР;
* производить исследования и анализ;

1.8 Руководитель проектов по созданию сайтов в своей деятельности руководствуется:

* Уставом университета;
* Положением об УСИиВС;
* Положением о веб-сайтах университета;
* Коллективным договором;
* Настоящей должностной инструкцией.

== 2. Основные функции и обязанности

2.1 Руководитель проектов по созданию сайтов в своей работе выполняет следующие функции:

* руководство и участие в разработке проектов создания, модернизации и текущей поддержке официальных сайтов университета;
* курирование проектов по созданию, модернизации и текущей поддержке иных веб-ресурсов университета;
* контроль и поддержание работоспособности официальных сайтов университета;
* администрирование официальных сайтов университета;
* организация работ по информационной поддержке официальных сайтов университета;
* организация работ по продвижению и поисковой оптимизации (SEO) официальных сайтов университета.
* участие в обучении и консультировании персонала в рамках своих компетенций.

2.2 При осуществлении своей деятельности руководитель проектов по созданию сайтов обязан:

* сбор и анализ требований к функциональности и оформлению сайта, создание сценариев использования функциональности сайта и отдельных модулей;
* формализация и контроль корректности выявленных требований;
* разработка требований к необходимым техническим ресурсам;
* разработка кода шаблонов и программных модулей на основе готовых спецификаций;
* отладка кода на уровне модулей, межмодульных взаимодействий и взаимодействий с пользователем и системой управления контента;
* проектирование распределенной и многопоточной организации создаваемых приложений;
* интеграция существующих и созданных программных компонент;
* анализ и оптимизация исполнимого кода и кода веб-страниц c использованием инструментальных средств, для повышения качества изделий и производительности разработки;
* планирование тестирования сайта и разработка тестовых наборов и процедур;
* разработка и ведение необходимой проектной и пользовательской документации;
* сдача документации и программного обеспечения заказчику;
* управление выполнением проекта, руководство проектной группой;
* взаимодействие с заказчиками, потенциальными пользователями, другими группами УСИиВС;
* оценка качества программных средств проекта;
* анализ эффективности инструментальных средств для выполнения проектов;
* участие в аттестации созданного программного обеспечения и шаблонов оформления;
* участие в совершенствовании процесса разработки в рабочих группах;
* участие в выработке проектных стандартов разработки;
* поисковая оптимизация страниц сайта (SEO), включая создание метаописаний;
* регистрация сайта в интернет-каталогах, в т.ч. тематических;
* консультация заинтересованного персонала (студентов университета, методистов кафедр) по основам веб-дизайна и управлению контентом сайта;
* создание на сайте информационных разделов для отделов и служб университета;
* обновление содержимого разделов на основе предоставленной информации;
* администрирование и модерирование форума и блогов, связь с пользователями;
* установка и настройка базового программного обеспечения веб-сервера;
* поиск и размещение на сайте материалов и ссылок, соответствующих тематике сайта; 
* планирование проекта и проведение совещаний по поводу эффективной работы сайта;
* управление персоналом в рамках выполнения проектов и работа в команде;
* анализ результатов выполненных проектов, и обобщение эффективных технологий и проектных решений;  
* планирование выполнения работ по совершенствованию процесса управления сайтом;
* развитие в себе аккуратности, аналитического мышления, методичности, ответственности, дисциплинированности, коммуникабельности, исполнительности, организованности и инициативности;
* планирование и организация собственной работы;
* организация самообучения и повышения своей квалификации;
* освоение новых методов и технологий в области информационных систем;
* чтение профессиональной литературы на английском языке;
* письменное и устное изложение своих предложений и полученных результатов для различных аудиторий.

2.3 При осуществлении своей деятельности руководитель проектов по созданию сайтов  должен:

* оценивать границы собственной компетентности;
* уметь организовывать работу курируемой рабочей группы;
* ответственно подходить к выполнению рабочих заданий;
* уметь работать в команде;
* сотрудничать с другими работниками в составе рабочей группы;
* поддерживать и актуализировать знания в областях профессиональной деятельности;
* проявлять новаторство и творческий подход в профессиональной деятельности;
* следить за новинками отечественной и зарубежной профессиональной литературы;
* рационально организовывать свой труд на рабочем месте;
* передавать опыт и знания работы;
* владеть культурой межличностного общения;
* формировать в себе аккуратность, дисциплинированность, вежливость, толерантность, ответственность, исполнительность, самостоятельность.

2.4. Руководитель проектов по созданию сайтов в области охраны труда обязан:

* соблюдать установленные трудовым законодательством, правилами и инструкциями требования охраны труда;
* правильно применять средства индивидуальной и коллективной защиты;
* проходить обучение безопасным методам и приемам выполнения работ и оказанию первой помощи пострадавшим на производстве, инструктаж по охране труда, стажировку на рабочем месте, проверку знаний требований охраны труда;
* немедленно извещать своего непосредственного или вышестоящего руководителя о любой ситуации, угрожающей жизни и здоровью людей, о каждом несчастном случае, происшедшем в управлении, или об ухудшении состояния своего здоровья, в том числе о проявлении признаков острого профессионального заболевания(отравления);
* проходить обязательные предварительные (при поступлении на работу) и периодические (в течение трудовой деятельности) медицинские осмотры (обследования), а также проходить внеочередные медицинские осмотры (обследования) по направлению работодателя в случаях, предусмотренных действующим трудовым законодательством и иными Федеральными законами.
* вносить предложения по улучшению и оздоровлению условий труда, а также доводить до сведения руководителя о всех недостатках в обеспечении трудового процесса, снижающих жизнедеятельность и работоспособность организма работников;
* немедленно сообщать своему непосредственному руководителю о каждом несчастном случае происшедшем с работником, немедленно оказывать первую доврачебную помощь пострадавшему, при необходимости отправлять его в лечебное учреждение.

== 3. Права

3.1 Руководитель проектов по созданию сайтов имеет право:

* знакомиться и участвовать в разработке проектов решений руководства университета и УСИиВС, касающихся его деятельности;
* вносить на рассмотрение руководства университета предложения по совершенствованию работы, связанной с предусмотренными настоящей инструкцией обязанностями;
* запрашивать лично или по поручению непосредственного руководителя у руководителей подразделений университета и специалистов информацию и документы, необходимые для выполнения его должностных обязанностей;
* требовать от руководства УСИиВС оказания содействия в исполнении своих должностных обязанностей;
* принимать решения в рамках профессиональной компетенции;
* участвовать в программах сертификации и повышения квалификации.

== 4. Ответственность

4.1 Руководитель проектов по созданию сайтов несет ответственность:

* за ненадлежащее исполнение или неисполнение своих должностных обязанностей, предусмотренных настоящей должностной инструкцией -- в порядке, установленном действующим трудовым законодательством Российской Федерации;
* за правонарушения, совершенные в процессе своей деятельности -- в порядке, установленном действующим административным, уголовным и гражданским законодательством Российской Федерации;
* за причинение ущерба университету -- в порядке, установленном действующим трудовым законодательством Российской Федерации;
* за некачественное выполнение порученной работы в установленные сроки, несоблюдение правил внутреннего трудового распорядка, техники безопасности и производственной санитарии;
* за несоблюдение правил делового общения, норм служебного этикета, служебной субординации.
