= Должностная инструкция менеджера по контенту

== 1 Общие положения

1.1 Менеджер по контенту группы поддержки сетевой архитектуры Управления информационно-коммуникационных технологий (УИКТ) далее менеджер по контенту относится к категории специалистов.

1.2 На должность менеджер по контенту назначается лицо, имеющее высшее профессиональное в области информационных технологий образование, без предъявления требований к стажу работы, или среднее профессиональное (техническое или инженерно-экономическое) образование и стаж работы в должности программиста не менее 1 года, либо других должностях в области информатизации и стаж работы не менее 2 лет. 

1.3 Назначение и освобождение от должности менеджер по контенту производится приказом ректора университета по представлению проректора по информатизации, согласованному с начальником УИКТ.

1.4 Менеджер по контенту должен знать, уметь и применять на практике:

* средства и методы объектно-ориентированного проектирования и разработки;
* основные принципы управления качеством;
* методы оценки сроков и стоимости разработки;
* внутренние нормы и регламенты разработки;
* принципы идентификации и планирования ресурсов;
* разработку и ведение проектной документации в соответствии со стандартами;
* основы защиты информации в сетях; использование протоколов SSL, TLS;
* основы организации и администрирования серверных ОС семейств Windows и Unix / Linux;
* администрирование веб-сервера (IIS 6/7/8, Apache); публикацию сайта в Интернет;
* основы организации сетей TCP/IP;
* основы теории организации и применения баз данных, иметь представление о MS SQL, MySQL;
* основы веб-дизайна и разработки эффективных пользовательских интерфейсов; 
* отраслевую нормативно-техническую документацию, специальную литературу;
* принципы архитектурного дизайна программного обеспечения, в частности, веб-приложений;
* стандартные алгоритмы и структуры данных, области их применимости;
* языковые средства веб-разработки: HTML+CSS, JavaScript, ASP.NET, AJAX, XML+XSL.
* инструментарий разработки веб-приложений: Visual Studio .NET, Dreamweaver, Aptana и др.;
* системы управления контентом: Dotnetnuke, Joomla! и др.;
* основы обработки и подготовки изображений и видеоматериалов к публикации, иметь опыт работы в Photoshop, Fireworks, GIMP, Inkscape, VirtualDUB и др.;
* принципы работы поисковых систем (Yandex, Google и др.);
* современные методы оптимизации веб-приложения для поисковых систем;
* методы анализа статистических характеристик текста, значимые для SEO.
* методы и способы продвижения сайта в поисковых системах;
* современные технологии в области работы ИТ-специалиста;
* русский язык и культуру речи;
* законы, инструкции и руководящие документы, необходимые для работы УИКТ;
* основы организации труда и законодательство о труде;
* правила внутреннего трудового распорядка;
* должностную инструкцию;
* профессиональную этику;
* корпоративную культуру;
* инструкции по охране труда;
* правила противопожарной безопасности;
* английский технический язык, специальную терминологию.

1.1 Менеджер по контенту в своей деятельности руководствуется:

* Уставом университета;
* положением об УИКТ;
* коллективным договором;
* настоящей должностной инструкцией.

== 2 Основные функции и обязанности

2.1 Основные функции менеджера по контенту:

* информационная поддержка официального сайта и других веб-проектов университета;
* продвижение сайтов и поисковая оптимизация (SEO); 
* администрирование официального сайта и других веб-проектов университета;
* участие в разработке проектов, расширяющих функциональность сайтов;
* обучение и консультирование персонала в рамках своей компетенции;
* тестирование и проверка правильности работы веб-сайтов в различных браузерах;
* контроль работоспособности официального сайта и других веб-проектов университета.

2.2 При осуществлении своей деятельности менеджер по контенту обязан:

* собирать и анализировать требования к функциональности и оформлению сайта, создавать сценарии использования функциональности сайта и отдельных модулей;
* разрабатывать код отдельных элементов веб-страниц на основе готовых спецификаций;
* анализировать и оптимизировать код веб-страниц c использованием инструментальных средств для повышения качества изделий и производительности разработки;
* взаимодействовать с пользователями и группами УИКТ;
* участвовать в аттестации созданного программного обеспечения и шаблонов оформления;
* заниматься поисковой оптимизацией контента сайта (SEO), включая создание метаописаний и специальных поисковых статей;
* участвовать в разработке и использовать таксономию сайта для эффективной категоризации контента;
* регистрировать сайты в интернет-каталогах, поисковых системах, в т.ч. тематических;
* проводить консультации заинтересованного персонала (студентов университета, методистов кафедр) по основам веб-дизайна и управлению контентом сайта;
* создавать на сайте информационные разделы для отделов и служб университета;
* обновлять содержимое разделов на основе предоставленной информации;
* производить оповещение ответственных за предоставление информации лиц об устаревшей и неверной информации на сайте.
* администрировать и модернизировать форумы и блоги;
* обеспечивать обратную связь с пользователями веб-сайта;
* производить поиск и размещение на сайте материалов и ссылок, соответствующих тематике сайта; 
* участвовать в планировании работ по совершенствованию процесса управления сайтом;
* внедрять новые методы и технологии в области информационных систем;
* составлять отчёты по результатам функционирования программно-технических средств;
* планировать свою работу на месяц, квартал вперед в соответствии с планом работы УИКТ;
* вести техническую и отчетную документацию (заявки, акты выполненных работ и пр.);
* представлять руководителю подразделения итоговые отчеты выполненной работы за месяц, квартал, год в конце каждого периода;
* фиксировать внештатные ситуации;
* выполнять внеплановые распоряжения, разовые служебные поручения руководства УИКТ, ректора (проректора) в пределах функций УИКТ.
* читать профессиональную литературу на английском языке.

2.3 При осуществлении своей деятельности менеджер по контенту должен:

* оценивать границы собственной компетентности;
* уметь работать в команде;
* сотрудничать с другими работниками в составе рабочей группы;
* один раз в два года повышать свой профессиональный уровень (проходить курсы переподготовки, посещать семинары повышения квалификации и т.д.) с получением подтверждающих документов;
* рационально организовывать свой труд на рабочем месте;
* формировать в себе аккуратность, дисциплинированность, ответственность, исполнительность, самостоятельность.

2.4 Менеджер по контенту в области охраны труда обязан:

* соблюдать установленные трудовым законодательством, правилами и инструкциями требования охраны труда;
* правильно применять средства индивидуальной и коллективной защиты;
* проходить обучение безопасным методам и приемам выполнения работ и оказанию первой помощи пострадавшим, инструктаж по охране труда, стажировку на рабочем месте, проверку знаний требований охраны труда;
* немедленно извещать своего непосредственного или вышестоящего руководителя о любой ситуации, угрожающей жизни и здоровью людей, о каждом несчастном случае, происшедшем в управлении, или об ухудшении состояния своего здоровья, в том числе о проявлении признаков острого профессионального заболевания(отравления);
* проходить обязательные предварительные (при поступлении на работу) и периодические (в течение трудовой деятельности) медицинские осмотры (обследования), а также проходить внеочередные медицинские осмотры (обследования) по направлению работодателя в случаях, предусмотренных действующим трудовым законодательством и иными Федеральными законами.
* вносить предложения по улучшению и оздоровлению условий труда, а также доводить до сведения руководителя о всех недостатках в обеспечении трудового процесса, снижающих жизнедеятельность и работоспособность организма работников;
* немедленно сообщать своему непосредственному руководителю о каждом несчастном случае происшедшем с работником, немедленно оказывать первую доврачебную помощь пострадавшему, при необходимости отправлять его в лечебное учреждение.

== 3 Права

3.1. Менеджер по контенту имеет право:

* знакомиться и участвовать в разработке проектов решений руководства университета и УИКТ, касающихся его деятельности;
* вносить на рассмотрение руководства университета предложения по совершенствованию работы, связанной с предусмотренными настоящей инструкцией обязанностями;
* запрашивать лично или по поручению непосредственного руководителя у руководителей подразделений университета и специалистов информацию и документы, необходимые для выполнения его должностных обязанностей;
* требовать от руководства УИКТ оказания содействия в исполнении своих должностных обязанностей;
* принимать решения в рамках профессиональной компетенции;
* участвовать в программах сертификации и повышения квалификации.


== 4 Ответственность

4.1. Менеджер по контенту несет ответственность:

* за ненадлежащее исполнение или неисполнение своих должностных обязанностей, предусмотренных настоящей должностной инструкцией - в порядке, установленном действующим трудовым законодательством Российской Федерации;
* за правонарушения, совершенные в процессе своей деятельности - в порядке, установленном действующим административным, уголовным и гражданским законодательством Российской Федерации;
* за причинение ущерба университету - в порядке, установленном действующим трудовым законодательством Российской Федерации;
* за некачественное выполнение порученной работы в установленные сроки, несоблюдение правил внутреннего трудового распорядка, техники безопасности и производственной санитарии;
* за несоблюдение правил делового общения, норм служебного этикета, служебной субординации.
