= Система сбора и публикации вакансий на сайте университета. Внешнее описание

== Назначение разработки

Система сбора и публикации вакансий на сайте университета при своей реализации позволит решить следующие задачи:

- упростить подачу информации о вакансиях для работодателей;
- улучшить информированность студентов университета о доступных вакансиях;
- обеспечить типизацию информации о вакансиях на сайте университета;
- по результатам использования системы, выявить требования к новым версиям системы.

В первоначальном варианте, систему для сбора и публикации вакансий предлагается реализовать в виде двух независимых компонент.

== Сбор вакансий

Сбор вакансий предполагается реализовать с использованием стандартного модуля Form & List.

=== Сценарий использования:

- Работодатель заполняет форму вакансии.
- При нажатии на кнопку "Отправить" на заранее определенный адрес электронной почты отправляется сообщение с данными о вакансии.

Вариант - сбор через багтрекер.

== Публикация вакансий

Публикацию вакансий на сайте университета предполагается реализовать с помощью специализированного расширения для платформы DNN, подлежащего разработке. Расширение предлагается разработать  на основе инструментария https://2sxc.org[2Sxc.org].

=== Сценарий использования:

- Редактор получает на заранее определенный адрес электронной почты сообщение с данными о вакансии.
- Редактор входит на сайт под своей учетной записью, переходит на страницу со списком вакансий, включает режим редактирования.
- Редактор переносит данные о вакансии из сообщения электронной почты в форму на сайте, в процессе осуществляя контроль и коррекцию информации.
- При нажатии на кнопку "Сохранить" данные вакансии публикуются на сайте.

В роли редактора выступает сотрудник отдела трудоустройства.

== Структура данных о вакансии

- Наименование компании (короткий текст)
- Описание компании (длинный текст)
- Наименование вакансии (короткий текст)
- Обязанности сотрудника (длинный текст)
- Требования к кандидату (длинный текст)
- Условия работы (длинный текст)
- Контактная информация работодателя (длинный текст)

== Дополнительные вопросы

Удаление, упорядочивание записей о вакансиях на сайте осуществляется с помощью стандартных средств инструментария https://2sxc.org[2Sxc.org].
